website/urls.py
from django.conf.urls import include, url, patterns
from django.conf import settings
from django.contrib import admin
from new_app.views import *
import notifications


admin.autodiscover()
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^firststep/([A-Z]+)/$', firstStep, name='firststep'),
    url(r'^$', home, name='home'),
    # url(r'^tracks/$', tracks, name='tracks'),
    # url(r'^track/([0-9]+)/$', track_details, name='track'),

    url(r'^newquestion/$', add_question, name='add_question'),
    url(r'^question/details/(?P<id>[0-9]+)/$', question_details, name='question_details'),


    url(r'^moderate/$', moderate, name='moderate'),
    url(r'^moderate/newquestions$', moderate_new_questions, name='moderate_new_questions'),
    url(r'^moderate/newanswers$', moderate_new_answers, name='moderate_new_answers'),
    url(r'^moderate/newmaterials$', moderate_new_materials, name='moderate_new_materials'),


    # url(r'^faq/$', FAQ, name='FAQs'),

    url(r'^vote/$', Vote, name='vote'),


    url(r'^materials/(?P<type>[a-zA-Z]+)/(?P<track_id>[0-9]*)$', materials, name='materials'),
    url(r'^questions/(?P<type>[a-zA-Z]+)/(?P<track_id>[0-9]*)$', questions, name='questions'),



    url(r'^newmaterial/$', add_material, name='add_material'),


    url(r'^approve/question$', approve_question, name='approve_question'),
    url(r'^reject/question$', reject_question, name='reject_question'),



    url(r'^approve/answer$', approve_answer, name='approve_answer'),
    url(r'^reject/answer$', reject_answer, name='reject_answer'),

    url(r'^approve/material$', approve_material, name='approve_material'),
    url(r'^reject/material$', reject_material, name='reject_material'),


    url(r'^notify/read$', notification_read, name='notification_read'),

    # url(r'^signup/$', SignUpView.as_view(), name='signup'),
    url(r'^signup/$', register, name='signup'),

    url(r'^testsearch/$', search_questions),

    url(r'^search/$', include('haystack.urls')),


]

urlpatterns += patterns(
    'django.contrib.auth.views',

    url(r'^login/$', 'login',{'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', 'logout',{'next_page': 'home'}, name='logout'),


                        )


if settings.DEBUG :
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )


urlpatterns += patterns('',
        url('^inbox/notifications/', include(notifications.urls)),
        url(r'^notification/$', 'new_app.views.notify', name='notification'),
    )

new_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from time import time


from django.db.models.signals import post_save
from notifications import notify
from django.utils.translation import ugettext_lazy as _




def get_upload_file_name(instance,filename):
    return 'images/%s/%s_%s'% (type(instance).__name__,str(time()).replace('.','_'),filename)


class SiteUser(models.Model):
    user = models.OneToOneField(User)

    def __unicode__(self):
        return self.user.username


class Track(models.Model):
    title = models.CharField(max_length=100)
    short_name = models.CharField(max_length=10)
    description = models.TextField()

    def __unicode__(self):
        return self.title



class Question(models.Model):

    type_choices = (
        ('IQ', 'IQ'),
        ('EN', 'English'),
        ('FAQ', 'FAQ'),
        ('SOFT', 'Soft Skills'),
        ('TRACK', 'Track'),
    )

    status_choices = (
        ('Pending', 'Pending'),
        ('Approved', 'Approved'),
        ('Rejected', 'Rejected'),
    )



    header = models.CharField(max_length=100)
    user_id = models.ForeignKey(User)
    track_id = models.ManyToManyField(Track, blank=True)

    type = models.CharField(choices=type_choices, max_length=10, default='TRACK')

    status = models.CharField(max_length=10,choices=status_choices, default=status_choices[1][0])


    image = models.ImageField(null=True,blank=True, upload_to=get_upload_file_name)
    voteUpUsers = models.ManyToManyField(User, blank=True,related_name='questionUpVotes')
    voteDownUsers = models.ManyToManyField(User, blank=True,related_name='questionDownVotes')


    created = models.DateTimeField(auto_now_add=True, null=True)
    modified = models.DateTimeField(auto_now=True, null=True)


    @property
    def votes(self):
        return self.voteUpUsers.count() - self.voteDownUsers.count()


    def userVote(self,user):
        if self.voteUpUsers.filter(pk=user.id).exists():
            return 1
        elif self.voteDownUsers.filter(pk=user.id).exists():
            return -1
        else:
            return 0

    def __unicode__(self):
        return self.header

class Answer(models.Model):

    status_choices = (
        ('Pending', 'Pending'),
        ('Approved', 'Approved'),
        ('Rejected', 'Rejected'),
    )

    body = models.TextField("Answer")
    question_id = models.ForeignKey(Question, related_name='answers')
    user_id = models.ForeignKey(User)


    voteUpUsers = models.ManyToManyField(User, blank=True,related_name='answerUpVotes')
    voteDownUsers = models.ManyToManyField(User, blank=True,related_name='answerDownVotes')


    status = models.CharField(max_length=10,choices=status_choices, default=status_choices[1][0])


    image = models.ImageField(null=True,blank=True, upload_to=get_upload_file_name)

    created = models.DateTimeField(auto_now_add=True, null=True)
    modified = models.DateTimeField(auto_now=True, null=True)


    @property
    def votes(self):
        return self.voteUpUsers.count() - self.voteDownUsers.count()


    def userVote(self,user):
        if self.voteUpUsers.filter(pk=user.id).exists():
            return 1
        elif self.voteDownUsers.filter(pk=user.id).exists():
            return -1
        else:
            return 0

    def __unicode__(self):
        return self.body


class Material(models.Model):

    status_choices = (
        ('Pending', 'Pending'),
        ('Approved', 'Approved'),
        ('Rejected', 'Rejected'),
    )

    type_choices = (
        ('IQ', 'IQ'),
        ('EN', 'English'),
        ('SOFT', 'Soft Skills'),
        ('TRACK', 'Track'),
    )

    name = models.CharField(max_length=100)
    link = models.URLField()
    type = models.CharField(choices=type_choices, max_length=10, default='TRACK')

    description = models.TextField(blank=True)
    user_id = models.ForeignKey(User)
    track_id = models.ManyToManyField(Track, blank=True)

    created = models.DateTimeField(auto_now_add=True, null=True)
    modified = models.DateTimeField(auto_now=True, null=True)

    status = models.CharField(max_length=10,choices=status_choices, default=status_choices[1][0])

    voteUpUsers = models.ManyToManyField(User, blank=True,related_name='materialUpVotes')
    voteDownUsers = models.ManyToManyField(User, blank=True,related_name='materialDownVotes')


    @property
    def votes(self):
        return self.voteUpUsers.count() - self.voteDownUsers.count()


    def userVote(self,user):
        if self.voteUpUsers.filter(pk=user.id).exists():
            return 1
        elif self.voteDownUsers.filter(pk=user.id).exists():
            return -1
        else:
            return 0


    def __unicode__(self):
        return self.name


class Type(models.Model):
    role = (
        ('HR', 'HR'),
        ('Technical', 'Technical'),
        ('Final', 'Final_interview') )
    role_type = models.CharField(max_length=1, choices=role)

    def __unicode__(self):
        return self.role_type


class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField(max_length=1200)
    date = models.CharField(max_length=100)
    type_name = models.ForeignKey(Type)

    created = models.DateTimeField(auto_now_add=True, null=True)
    modified = models.DateTimeField(auto_now=True, null=True)

    def __unicode__(self):
        return self.title




def my_handler(sender, instance, created, **kwargs):
    question = instance.question_id
    question_user = question.user_id
    answer_user = instance.user_id

    users_set = set()
    users_set.add(question_user)

    notify.send(recipient=question_user, sender=instance.user_id, verb='Answered', target=question)
    for answer in question.answers.all():
        if answer.user_id != answer_user and answer.user_id != question_user:
            notify.send(recipient=answer.user_id, sender=instance.user_id, verb=_('Answered'), target=question)
            users_set.add(answer.user_id)


post_save.connect(my_handler, sender=Answer)

new_app/forms.py
from django import forms
from django.forms import ModelForm
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import UserCreationForm
from captcha.fields import ReCaptchaField

from models import *



class QuestionForm(ModelForm):
    header = forms.CharField(label=_('Question'))
    type = forms.ChoiceField(label=_('Question Type'),choices=Question.type_choices)
    track_id = forms.ModelMultipleChoiceField(label=_('Choose Tracks'), queryset=Track.objects.all(), widget=forms.CheckboxSelectMultiple,required=False )
    image = forms.ImageField(label=_('Image'),required=False)
    class Meta:
        model = Question
        fields = ['header','type', 'track_id','image', 'user_id' ]


class AnswerForm(ModelForm):
    body = forms.CharField(widget=forms.Textarea(),label=_('body'))

    image = forms.ImageField(label=_('Image'), required=False)

    class Meta:
        model = Answer
        fields = ['question_id','body','image', 'user_id' ]



class MaterialForm(ModelForm):
    name = forms.CharField(label=_('Title'))
    description = forms.CharField(widget=forms.Textarea(),label=_('Description'),required=False)
    link = forms.URLField(label=_('Link'))
    type = forms.ChoiceField(label=_('Material Type'),choices=Material.type_choices)
    track_id = forms.ModelMultipleChoiceField(label=_('Choose Tracks'), queryset=Track.objects.all(), widget=forms.CheckboxSelectMultiple,required=False )

    class Meta:
        model = Material
        fields = ['name','description', 'link','type', 'track_id', 'user_id' ]


class registerationForm(UserCreationForm):
    captcha = ReCaptchaField(attrs={'theme' : 'clean'})

new_app/templates/addmaterial.html
{% extends 'base.html' %}



{% block maincontent %}


    {% load widget_tweaks %}
    {% load crispy_forms_tags %}

    {% if msg%}
    <div class="alert alert-success">
    {{ msg }}
    </div>
    {% endif %}


    <div class="well col-md-6 col-md-offset-3">
        <fieldset>
            <legend>
أضف ماتيريال
            </legend>
            <div class="panel-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form | crispy }}

                    <p><input class="btn btn-success pull-right" type="submit" value="إرسال" /></p>
                </form>
            </div>
        </fieldset>

    </div>



{% endblock maincontent %}




{% block js %}
    <script>

        function checkTrack(){

            if ($('#id_type').val() == 'TRACK'){
                $('#div_id_track_id').show();

            } else {
                $('#div_id_track_id').hide();

            }
        }

        checkTrack();

        $('#id_type').on('change',function(){
            checkTrack();
        })



    </script>
    {% endblock %}

new_app/templates/addquestion.html
{% extends 'base.html' %}



{% block maincontent %}


    {% load widget_tweaks %}
    {% load crispy_forms_tags %}

    {% if msg%}
    <div class="alert alert-success">
    {{ msg }}
    </div>
    {% endif %}


    <div class="well col-md-6 col-md-offset-3">
        <fieldset>
            <legend>
اسأل سؤال
            </legend>
            <div class="panel-body">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}

                    <p><input class="btn btn-success pull-right" type="submit" value="إرسال" /></p>
                </form>
            </div>
        </fieldset>

    </div>



{% endblock maincontent %}




{% block js %}
    <script>

        function checkTrack(){

            if ($('#id_type').val() == 'TRACK'){
                $('#div_id_track_id').show();
            } else {
                $('#div_id_track_id').hide();
            }
        }

        checkTrack();

        $('#id_type').on('change',function(){
            checkTrack();
        })



    </script>
    {% endblock %}

new_app/templates/base.html
{% load staticfiles %}

{% load i18n %}
<!DOCTYPE html>
<html lang="ar">
<!--    xmlns="http://www.w3.org/1999/xhtml"-->
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-142460601-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-142460601-1');
    </script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


{#    <link href=" {% static 'css/bootstrap-cerulean.min.css' %}" rel="stylesheet"/>#}
    <link href=" {% static 'css/bootstrap1.min.css' %}" rel="stylesheet"/>
    <link href=" {% static 'css/bootstrap-flipped.min.css' %}" rel="stylesheet"/>
    <link href=" {% static 'css/font-awesome.min.css' %}" rel="stylesheet"/>
    <link href=" {% static 'css/prettyPhoto.css' %}" rel="stylesheet"/>
    <link href=" {% static 'css/animate.css' %}" rel="stylesheet"/>
    <link href=" {% static 'css/main.css' %}" rel="stylesheet"/>

    
    <!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

{#    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>#}
    <link href="{% static 'css/mystyle.css' %}" rel="stylesheet"/>



    <title>موقع الإعداد لمنحة ITI</title>
</head>


<body>


<div class="container-fluid">

{#    <div class="jumbotron">#}
{#        <h1>ITI Prepare</h1>#}
{##}
{#        <p>#}
{#            موقع الإعداد لمنحة معهد تكنولوجيا المعلومات التابع لوزارة الإتصالات#}
{#        </p>#}
{#    </div>#}

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

        <div class="navbar-header">

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
{#        <a class="navbar-brand" href="#"><!--<img src="images/logo.PNG" alt="iti" class="logo" />--></a>#}
        <a class="navbar-brand" href="{% url 'home' %}">ITI Prepare</a>

        <div class="navbar-collapse collapse">


            <ul class="nav navbar-nav navbar-left">
                {% if not user.is_authenticated %}
                    <li><a href="{% url 'login' %}">تسجيل دخول</a></li>
                    <li><a href="{% url 'signup' %}">إنشاء حساب</a></li>
                 {% else %}
                    <li><a>
                        مرحباً, {{ user.username }}</a></li>


                    <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        {% trans 'notifications' %}
                        {% if notifications|length != 0 %}
                        <span class="badge" id="notify">{{ notifications|length }}</span>
                        {% endif %}
                    <span class="caret"></span>
                    </a>

                        <ul  class="dropdown-menu" style="width: 270px;">
                            {% for notify in notifications %}
                            <li id="{{ notify.target.id }}">
                                <a onclick="notification_read({{ notify.target.id }})"><span class="close" style="color: #ffffff;">x</span> </a>
                                <a onclick="notification_read({{ notify.target.id }})" href="{% url 'question_details' notify.target.id %}" style="white-space: normal;">

                                <strong>
                                {{ notify.actor }}
                                </strong>
                                {% if notify.others != 0 %}
                                    {% trans 'and' %}
                                    {{ notify.others }}
                                    {% trans 'others' %}
                                {% endif %}
                                {% trans 'Answered' %}
                                <strong>
                                {{ notify.target }}
                                    </strong>
                                <br />
                                <small>
                                {% trans 'since' %}
                                {{ notify.timesince }}
                                    </small>

                            </a></li>

{#                                <li><a >{{ notify.target.id }}</a></li>#}
                            {% empty %}
                                <li><a >{% trans 'No new notifications' %}</a></li>
                            {% endfor %}
                        </ul>
                </li>
                    <li><a href="{% url 'logout' %}">
                        تسجيل الخروج
                        </a></li>
                    {% if user.is_staff %}
                    <li><a href="{% url 'moderate' %}">
الإدارة
                        </a></li>
                    {% endif %}
                {% endif %}
            </ul>





            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>

{#                <li><a href="#contact">مراحل التقديم </a></li>#}
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        {% trans 'first step' %}
                    <span class="caret"></span>
                    </a>

                        <ul  class="dropdown-menu">

                            <li><a href="{% url 'materials' 'EN' '' %}">English</a></li>
                            <li><a href="{% url 'materials' 'IQ' '' %}">IQ</a></li>
                            <li><a href="{% url 'materials' 'SOFT' '' %}">Soft Skills</a></li>
                        </ul>
                </li>
                <li class="dropdown">

                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        {% trans 'Tracks' %}
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu scrollable-menu">
                        {% for track in tracks %}
                            <li><a href="{% url 'materials' 'TRACK' track.id %}">{{ track.title }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li><a href="{% url 'questions' 'FAQ' '' %}">{% trans 'FAQ' %}</a></li>


            </ul>
        </div>
    </nav>


</div>

<!--main content-->
<div class="container main-content" style="margin-bottom: 20px;">




    {% block maincontent %}
    {% endblock maincontent %}


</div>



{#<footer class="navbar navbar-inverse navbar-fixed-bottom">#}
{#    <span> Copyright © 2015 <a href="index.html" class="link"> </a>  . All rights reserved</span>#}
{#</footer>#}

    <script src="{% static 'js/jquery.min.js' %}"></script>


    <script src="{% static 'js/bootstrap-arabic.min.js' %}"></script>

    <script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
    <script src="{% static 'js/jquery.isotope.min.js' %}"></script>

    <script src="{% static 'js/ajax_setup.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

{% block js %}

{% endblock %}

</body>
</html>

new_app/templates/login.html
{% extends 'base.html' %}


{% block maincontent %}


    {% load widget_tweaks %}
    {% load crispy_forms_tags %}

    <div class="well col-md-6 col-md-offset-3">
        <fieldset>
            <legend>
تسجيل الدخول
            </legend>
            <div class="panel-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <input type="hidden" name="next" value="{{ next }}">
                    <p><input class="btn btn-success pull-right" type="submit" value="تسجيل" /></p>
                </form>
            </div>
        </fieldset>

    </div>


{% endblock maincontent %}

new_app/templates/materials.html
{% extends 'base.html' %}

{% load my_filters %}
{% load i18n %}

{% load bootstrap3 %}

{% block maincontent %}
<div class="row">

{% if track %}

{% include 'track.html' %}

{% endif %}


<div class="col-md-12 well">

    <div class="tabbable tabs-right">
        <ul class="nav nav-tabs">
            <li class="active"><a href="{% url 'materials' type track.id %}">{% trans 'Material' %}</a></li>
            <li ><a href="{% url 'questions' type track.id %}">{% trans 'questions' %}</a></li>
            <li ><a href="{% url 'questions' type track.id %}?u=t">{% trans 'unanswered questions' %}</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active t">

                <h2>
{% trans 'Material' %}
                    {% if user.is_authenticated %}
<a href="{% url 'add_material' %}" class="pull-right btn btn-success">
    <span class="glyphicon glyphicon-plus"></span>

    {% trans "Add Material" %}

</a>
{% endif %}
                </h2>

                <div class="panel-group" id="accordion1" role="tablist" aria-multiselectable="true">
                    {% for material in materials|sort_votes %}

                        <div class="panel panel-info">
                            <div class="panel-heading" id="heading{{ material.id }}">
                                <h3 class="panel-title" style="position: relative;">
                                    <div class="text-center col-md-1">

                                    <div  {% if not user.is_authenticated %} style="visibility: hidden;"{% endif %}>
                                        <a href="#" onclick="Vote('m',{{ material.id }},1, event)"><span
                                                class="glyphicon glyphicon-thumbs-up text-success"> </span></a>
                                    </div>

                                    <div>
                                                <span class="badge label-info" id="m{{ material.id }}">
                                                    {{ material.votes }}
                                                </span>

                                    </div>

                                    <div {% if not user.is_authenticated %} style="visibility: hidden;"{% endif %}>
                                        <a href="#" onclick="Vote('m',{{ material.id }},-1, event)"><span
                                                class="glyphicon glyphicon-thumbs-down text-danger"> </span></a>
                                    </div>

                                </div>
                                    <a data-toggle="collapse" data-parent="#accordion1"
                                       href="#collapse{{ material.id }}" aria-expanded="true"
                                       aria-controls="collapse{{ material.id }}">
                                        {{ material.name }}
                                    </a>
                                <br />

                                <div class="h6 col-md-offset-1" style="position: absolute; bottom: 0px;">

                                    {% trans "Sent By:" %}
                                    {{ material.user_id }}
                                    |
                                    {% trans "Created at:" %}
                                    {{ material.created }}
                                    |
                                    {% trans "Last Modified:" %}
                                    {{ material.modified }}
                                </div>

                                <div class="clearfix"></div>
                                </h3>
                            </div>
                            <div id="collapse{{ material.id }}" class="panel-collapse collapse" role="tabpanel"
                                 aria-labelledby="heading{{ material.id }}">
                                <div class="panel-body">
                                    {{ material.description }}
                                </div>
                                <div class="panel-footer">
                                    <a href="{{ material.link }}" class="btn btn-primary" target="_blank">
                                        تحميل
                                    </a>
                                </div>
                            </div>
                        </div>





                    {% endfor %}
                <div class="center">
                                {% bootstrap_pagination materials %}

                    </div>
                </div>
            </div>


        </div>
    </div>


</div>

</div>
{% endblock %}

new_app/templates/notify.html
{{ notifications }}

new_app/templates/search.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

    <form method="post">
        {% csrf_token %}
        <input type="text" name="search_text">
        <input type="submit" value="Submit">

    </form>

    <ul>
        {% for q in questions %}
            <li>{{ q.object.header}}{{ q.object.get_absolute_url }}</li>
        {% endfor %}
    </ul>





</body>
</html>

new_app/templates/signup.html
{% extends 'base.html' %}


{% block maincontent %}


    {% load widget_tweaks %}
    {% load crispy_forms_tags %}

    <div class="well col-md-6 col-md-offset-3">
        <fieldset>
            <legend>
                تسجيل حساب
            </legend>
            <div class="panel-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form | crispy }}

                    <p><input class="btn btn-success pull-right" type="submit" value="تسجيل" /></p>
                </form>
            </div>
        </fieldset>

    </div>


{% endblock maincontent %}

new_app/templates/track.html
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">
                    {{ track.title }}
                </h3>
            </div>
            <div class="panel-body">
                {{ track.description }}
            </div>
        </div>

new_app/templates/tracks.html
{% extends 'base.html' %}


{% block maincontent %}


    <div class="row">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">
                    {{ track.title }}
                </h3>
            </div>
            <div class="panel-body">
                {{ track.description }}
            </div>
        </div>



    {% include 'questions-materials.html' %}
    </div>


{% endblock maincontent %}